[package]
name = "player_control"
version = "0.1.0"
authors = ["Daniel Hertenstein <daniel.hertenstein@gmail.com>"]
edition = "2018"

[dependencies]
tcod = "0.13.0"
game_state = { path = "../game_state" }
